"""add_transaction_table

Revision ID: 37d987c6ff7f
Revises: 2261b32d8440
Create Date: 2026-06-24 04:06:40.883642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "37d987c6ff7f"
down_revision: Union[str, None] = "2261b32d8440"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("amount", sa.Numeric(scale=2), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False
        ),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "Deposit",
                "Withdrawal",
                "Transfer",
                "Reversal",
                "Fee_Charged",
                "Loan_Disbursement",
                "Load_Repayment",
                "Interest_Credited",
                name="transactiontypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "transaction_category",
            sa.Enum("Credit", "Debit", name="transactioncategoryenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "Pending",
                "Completed",
                "Failed",
                "Reversed",
                "Cancelled",
                name="transactionstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("balance_before", sa.Numeric(scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(scale=2), nullable=False),
        sa.Column("failed_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender_account_id", sa.Uuid(), nullable=True),
        sa.Column("receiver_account_id", sa.Uuid(), nullable=True),
        sa.Column("sender_id", sa.Uuid(), nullable=True),
        sa.Column("receiver_id", sa.Uuid(), nullable=True),
        sa.Column("processed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "transaction_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["processed_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_account_id"],
            ["bankaccount.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_account_id"],
            ["bankaccount.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_reference"), "transaction", ["reference"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_reference"), table_name="transaction")
    op.drop_table("transaction")
    # ### end Alembic commands ###
