"""add_next_of_kin_table

Revision ID: 78e1564cf4af
Revises: aa3646b95e15
Create Date: 2026-06-23 04:17:04.876488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78e1564cf4af"
down_revision: Union[str, None] = "aa3646b95e15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


relationship_type_enum = postgresql.ENUM(
    "Spouse",
    "Parent",
    "Child",
    "Sibling",
    "Other",
    name="relationshiptypeenum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    relationship_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "nextofkin",
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("relationship", relationship_type_enum, nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("passport_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nextofkin")
    relationship_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
