"""add_bank_account_table

Revision ID: 7bbd65da4350
Revises: 78e1564cf4af
Create Date: 2026-06-23 08:37:15.303235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7bbd65da4350"
down_revision: Union[str, None] = "78e1564cf4af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


account_type_enum = postgresql.ENUM(
    "Current",
    "Savings",
    "FixedDeposit",
    "Business",
    name="accounttypeenum",
    create_type=False,
)
account_currency_enum = postgresql.ENUM(
    "USD",
    "EUR",
    "GBP",
    "KES",
    "THB",
    name="accountcurrencyenum",
    create_type=False,
)
account_status_enum = postgresql.ENUM(
    "Active",
    "Inactive",
    "Pending",
    "Closed",
    "Frozen",
    name="accountstatusenum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    account_type_enum.create(bind, checkfirst=True)
    account_currency_enum.create(bind, checkfirst=True)
    account_status_enum.create(bind, checkfirst=True)

    op.create_table(
        "bankaccount",
        sa.Column("account_type", account_type_enum, nullable=False),
        sa.Column("currency", account_currency_enum, nullable=False),
        sa.Column("account_status", account_status_enum, nullable=False),
        sa.Column("account_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("kyc_submitted", sa.Boolean(), nullable=False),
        sa.Column("kyc_verified", sa.Boolean(), nullable=False),
        sa.Column("kyc_verified_by", sa.Uuid(), nullable=True),
        sa.Column("interest_rate", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("kyc_verified_on", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bankaccount_account_number"),
        "bankaccount",
        ["account_number"],
        unique=True,
    )
    op.drop_constraint("nextofkin_user_id_fkey", "nextofkin", type_="foreignkey")
    op.create_foreign_key(
        "nextofkin_user_id_fkey",
        "nextofkin",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("profile_user_id_fkey", "profile", type_="foreignkey")
    op.create_foreign_key(
        "profile_user_id_fkey",
        "profile",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile_user_id_fkey", "profile", type_="foreignkey")
    op.create_foreign_key("profile_user_id_fkey", "profile", "user", ["user_id"], ["id"])
    op.drop_constraint("nextofkin_user_id_fkey", "nextofkin", type_="foreignkey")
    op.create_foreign_key(
        "nextofkin_user_id_fkey", "nextofkin", "user", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_bankaccount_account_number"), table_name="bankaccount")
    op.drop_table("bankaccount")

    bind = op.get_bind()
    account_status_enum.drop(bind, checkfirst=True)
    account_currency_enum.drop(bind, checkfirst=True)
    account_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
