"""add_idempotency_key_table

Revision ID: 8757556ec96b
Revises: 37d987c6ff7f
Create Date: 2026-06-24 06:55:56.917205

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8757556ec96b'
down_revision: Union[str, None] = '37d987c6ff7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS idempotencykey (
            id UUID NOT NULL,
            key VARCHAR NOT NULL,
            user_id UUID NOT NULL,
            endpoint VARCHAR NOT NULL,
            response_code INTEGER NOT NULL,
            response_body JSONB,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES "user" (id)
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ix_idempotencykey_key
        ON idempotencykey (key)
        """
    )
    op.execute(
        """
        ALTER TABLE nextofkin
            ADD COLUMN IF NOT EXISTS created_at
            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
        """
    )
    op.execute("ALTER TABLE nextofkin DROP COLUMN IF EXISTS create_at")
    op.execute(
        """
        ALTER TABLE "transaction"
            ADD COLUMN IF NOT EXISTS created_at
            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
        """
    )
    op.execute('ALTER TABLE "transaction" DROP COLUMN IF EXISTS create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE "transaction"
            ADD COLUMN IF NOT EXISTS create_at
            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
        """
    )
    op.execute('ALTER TABLE "transaction" DROP COLUMN IF EXISTS created_at')
    op.execute(
        """
        ALTER TABLE nextofkin
            ADD COLUMN IF NOT EXISTS create_at
            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
        """
    )
    op.execute("ALTER TABLE nextofkin DROP COLUMN IF EXISTS created_at")
    op.execute("DROP INDEX IF EXISTS ix_idempotencykey_key")
    op.execute("DROP TABLE IF EXISTS idempotencykey")
    # ### end Alembic commands ###
