"""add_risk_score_model

Revision ID: 96e5085e32d7
Revises: 6f4a8c2d9b10
Create Date: 2026-06-27 18:34:40.367325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "96e5085e32d7"
down_revision: Union[str, None] = "6f4a8c2d9b10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
            CREATE TYPE aireviewstatusenum AS ENUM (
                'PENDING',
                'FLAGGED',
                'CLEARED',
                'CONFIRMED_FRAUD'
            );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "transaction",
        sa.Column(
            "ai_review_status",
            sa.Enum(
                "PENDING",
                "FLAGGED",
                "CLEARED",
                "CONFIRMED_FRAUD",
                name="aireviewstatusenum",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "ai_review_status")
    op.execute("DROP TYPE aireviewstatusenum")
    # ### end Alembic commands ###
