"""fix_typo

Revision ID: 99ba263591ca
Revises: 8757556ec96b
Create Date: 2026-06-24 16:54:15.365241

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99ba263591ca'
down_revision: Union[str, None] = '8757556ec96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE idempotencykey
            ADD COLUMN IF NOT EXISTS expires_at
            TIMESTAMP WITH TIME ZONE
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'idempotencykey'
                  AND column_name = 'expies_at'
            ) THEN
                EXECUTE 'UPDATE idempotencykey
                         SET expires_at = expies_at
                         WHERE expires_at IS NULL';
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        UPDATE idempotencykey
        SET expires_at = created_at + INTERVAL '24 hours'
        WHERE expires_at IS NULL
        """
    )
    op.execute(
        """
        ALTER TABLE idempotencykey
            ALTER COLUMN expires_at SET NOT NULL
        """
    )
    op.execute("ALTER TABLE idempotencykey DROP COLUMN IF EXISTS expies_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE idempotencykey
            ADD COLUMN IF NOT EXISTS expies_at
            TIMESTAMP WITH TIME ZONE
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'idempotencykey'
                  AND column_name = 'expires_at'
            ) THEN
                EXECUTE 'UPDATE idempotencykey
                         SET expies_at = expires_at
                         WHERE expies_at IS NULL';
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        ALTER TABLE idempotencykey
            ALTER COLUMN expies_at SET NOT NULL
        """
    )
    op.execute("ALTER TABLE idempotencykey DROP COLUMN IF EXISTS expires_at")
    # ### end Alembic commands ###
